import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Category } from './core/models/category.model';
import { Entry, EntryType } from './core/models/entry.model';

export class InMemoryDatabase implements InMemoryDbService {
  createDb(): any {
    const categories: Category[] = [
      { id: 1, name: 'Moradia', desc: 'Pagamentos de Contas da Casa' },
      { id: 2, name: 'Saúde', desc: 'Plano de Saúde e Remédios' },
      { id: 3, name: 'Lazer', desc: 'Cinema, parques, praia, etc' },
      { id: 4, name: 'Salário', desc: 'Recebimento de Salário' },
      { id: 5, name: 'Freelance', desc: 'Trabalhos como freelancer' },
    ];

    const entries: Entry[] = [
      {
        id: 1,
        name: 'Gás de Cozinha',
        category: categories[0],
        paid: true,
        date: '14/01/2024',
        amount: '70,80',
        type: EntryType.Despesa,
        desc: 'Qualquer descrição para essa despesa',
      } as Entry,
      {
        id: 2,
        name: 'Suplementos',
        category: categories[1],
        paid: false,
        date: '14/01/2024',
        amount: '15,00',
        type: EntryType.Despesa,
      } as Entry,
      {
        id: 3,
        name: 'Salário na Empresa X',
        category: categories[3],
        paid: true,
        date: '15/01/2024',
        amount: '4405,49',
        type: EntryType.Receita,
      } as Entry,
      {
        id: 4,
        name: 'Aluguel de Filme',
        category: categories[2],
        paid: true,
        date: '16/01/2024',
        amount: '15,00',
        type: EntryType.Despesa,
      } as Entry,
      {
        id: 5,
        name: 'Suplementos',
        category: categories[1],
        paid: true,
        date: '17/01/2024',
        amount: '30,00',
        type: EntryType.Despesa,
      } as Entry,
      {
        id: 6,
        name: 'Video Game da Filha',
        category: categories[2],
        paid: false,
        date: '17/01/2024',
        amount: '15,00',
        type: EntryType.Despesa,
      } as Entry,
      {
        id: 12,
        name: 'Uber',
        category: categories[1],
        paid: true,
        date: '17/01/2024',
        amount: '30,00',
        type: EntryType.Despesa,
      } as Entry,
      {
        id: 12,
        name: 'Aluguel',
        category: categories[2],
        paid: false,
        date: '23/01/2024',
        amount: '15,00',
        type: EntryType.Despesa,
      } as Entry,
      {
        id: 13,
        name: 'Gás de Cozinha',
        category: categories[1],
        paid: false,
        date: '25/01/2024',
        amount: '30,00',
        type: EntryType.Despesa,
      } as Entry,
      {
        id: 14,
        name: 'Pagamento Pelo Projeto XYZ',
        category: categories[4],
        paid: true,
        date: '25/01/2024',
        amount: '2980,00',
        type: EntryType.Receita,
      } as Entry,
      {
        id: 19,
        name: 'Aluguel de Filme',
        category: categories[2],
        paid: false,
        date: '07/12/2023',
        amount: '15,00',
        type: EntryType.Despesa,
      } as Entry,
      {
        id: 21,
        name: 'Video Game da Filha',
        category: categories[1],
        paid: true,
        date: '17/12/2023',
        amount: '30,00',
        type: EntryType.Despesa,
      } as Entry,
      {
        id: 22,
        name: 'Cinema',
        category: categories[2],
        paid: true,
        date: '18/12/2023',
        amount: '15,00',
        type: EntryType.Despesa,
      } as Entry,
      {
        id: 23,
        name: 'Jiu Jitsu',
        category: categories[1],
        paid: false,
        date: '21/12/2023',
        amount: '130,00',
        type: EntryType.Despesa,
      } as Entry,
      {
        id: 44,
        name: 'Uber',
        category: categories[2],
        paid: true,
        date: '28/12/2023',
        amount: '15,00',
        type: EntryType.Despesa,
      } as Entry,
      {
        id: 55,
        name: 'Cinema',
        category: categories[1],
        paid: false,
        date: '28/12/2023',
        amount: '30,00',
        type: EntryType.Despesa,
      } as Entry,
    ];

    return { categories, entries };
  }
}
